In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

In [2]:
raw_data: pd.DataFrame = pd.read_csv(
    filepath_or_buffer="../../../data/MOS2E03230475_30Hz_proc.csv",
    index_col=0,
    nrows=100,
    # nrows=4559526,
)

In [5]:
raw_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 100 entries, MOS2E03230475 to MOS2E03230475
Data columns (total 38 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   nickname             0 non-null      float64
 1   animalID             0 non-null      float64
 2   sample_rate          100 non-null    int64
 3   timestamps           100 non-null    object
 4   acc_axis1            100 non-null    float64
 5   acc_axis2            100 non-null    float64
 6   acc_axis3            100 non-null    float64
 7   acc_mag              100 non-null    float64
 8   lpf_axis1            100 non-null    float64
 9   lpf_axis2            100 non-null    float64
 10  lpf_axis3            100 non-null    float64
 11  lpf_mag              100 non-null    float64
 12  hpf_axis1            100 non-null    float64
 13  hpf_axis2            100 non-null    float64
 14  hpf_axis3            100 non-null    float64
 15  hpf_mag              100 non-null    float64
 16  spd_axis1            100 non-null    float64
 17  spd_axis2            100 non-null    float64
 18  spd_axis3            100 non-null    float64
 19  spd_mag              100 non-null    float64
 20  spd_axis1_denoised   100 non-null    float64
 21  spd_axis2_denoised   100 non-null    float64
 22  spd_axis3_denoised   100 non-null    float64
 23  spd_mag_denoised     100 non-null    float64
 24  dis_axis1            100 non-null    float64
 25  dis_axis2            100 non-null    float64
 26  dis_axis3            100 non-null    float64
 27  dis_mag              100 non-null    float64
 28  dis_axis1_denoised   100 non-null    float64
 29  dis_axis2_denoised   100 non-null    float64
 30  dis_axis3_denoised   100 non-null    float64
 31  dis_mag_denoised     100 non-null    float64
 32  tilt_axis1           100 non-null    float64
 33  tilt_axis2           100 non-null    float64
 34  tilt_axis3           100 non-null    float64
 35  tilt_axis1_denoised  100 non-null    float64
 36  tilt_axis2_denoised  100 non-null    float64
 37  tilt_axis3_denoised  100 non-null    float64
dtypes: float64(36), int64(1), object(1)
memory usage: 30.5+ KB

In [4]:
raw_data.sort_values(
    by=["Timestamp"],
    ascending=True,
    inplace=True,
)

KeyError: 'Timestamp'

In [ ]:
raw_data["Date"] = pd.to_datetime(
    raw_data["Timestamp"],
).dt.strftime(date_format="%d/%m/%Y")

raw_data["Time"] = pd.to_datetime(
    raw_data["Timestamp"],
).dt.strftime(date_format="%H:%M:%S")

In [ ]:
from itertools import cycle

c: cycle = cycle(range(1, 31))
raw_data["ID"] = [next(c) for _ in range(len(raw_data))]

In [ ]:
raw_data.drop(
    columns=[
        "SensorID",
        "HalterID",
        "CollarID",
        "CowID",
        "Orientation",
        "Timestamp",
    ],
    inplace=True,
)

raw_data.rename(
    columns={
        "X": "X_axis",
        "Y": "y_axis",
        "Z": "z_axis",
    },
    inplace=True,
)

In [ ]:
column_order: list[str] = ["Time", "ID", "Date", "X_axis", "y_axis", "z_axis"]
raw_data = raw_data.reindex(columns=column_order)

In [ ]:
raw_data.head(31)

        Time  ID        Date  X_axis  y_axis  z_axis
0   18:00:00   1  14/04/2023  -0.055   0.539   0.859
1   18:00:00   2  14/04/2023  -0.074   0.527   0.852
2   18:00:00   3  14/04/2023  -0.074   0.527   0.852
3   18:00:00   4  14/04/2023  -0.074   0.527   0.855
4   18:00:00   5  14/04/2023  -0.078   0.527   0.855
5   18:00:00   6  14/04/2023  -0.074   0.523   0.852
6   18:00:00   7  14/04/2023  -0.078   0.520   0.855
7   18:00:00   8  14/04/2023  -0.074   0.523   0.855
8   18:00:00   9  14/04/2023  -0.074   0.520   0.852
9   18:00:00  10  14/04/2023  -0.074   0.523   0.855
10  18:00:00  11  14/04/2023  -0.074   0.520   0.852
11  18:00:00  12  14/04/2023  -0.074   0.527   0.855
12  18:00:00  13  14/04/2023  -0.074   0.520   0.852
13  18:00:00  14  14/04/2023  -0.074   0.520   0.852
14  18:00:00  15  14/04/2023  -0.078   0.523   0.852
15  18:00:00  16  14/04/2023  -0.066   0.527   0.855
16  18:00:00  17  14/04/2023  -0.078   0.523   0.852
17  18:00:00  18  14/04/2023  -0.078   0.523   0.852
18  18:00:00  19  14/04/2023  -0.078   0.520   0.855
19  18:00:00  20  14/04/2023  -0.082   0.523   0.855
20  18:00:00  21  14/04/2023  -0.074   0.527   0.852
21  18:00:00  22  14/04/2023  -0.078   0.523   0.852
22  18:00:00  23  14/04/2023  -0.078   0.527   0.855
23  18:00:00  24  14/04/2023  -0.078   0.520   0.855
24  18:00:00  25  14/04/2023  -0.078   0.527   0.855
25  18:00:00  26  14/04/2023  -0.074   0.520   0.852
26  18:00:00  27  14/04/2023  -0.074   0.523   0.855
27  18:00:00  28  14/04/2023  -0.078   0.523   0.855
28  18:00:00  29  14/04/2023  -0.070   0.520   0.848
29  18:00:00  30  14/04/2023  -0.074   0.520   0.852
30  18:00:01   1  14/04/2023  -0.070   0.523   0.852

In [ ]:
raw_data.to_csv(
    path_or_buf="../../../data/COW62_fri.txt",
    index=None,
    header=True,
    sep=" ",
)